// Code generated by go generate; DO NOT EDIT.
// Source: FWSS contracts on mainnet, calibration, and devnet

package constants

import "github.com/ethereum/go-ethereum/common"

// root of trust - FWSS contract addresses
var (
	FWSSAddressMainnet     = common.HexToAddress("0x8408502033C418E1bbC97cE9ac48E5528F371A9f")
	FWSSAddressCalibration = common.HexToAddress("0x02925630df557F957f70E112bA06e50965417CA0")
	FWSSAddressDevnet      = common.HexToAddress("0x4A8a81765bFBe09D6fDd167EF954a1D3401340e5")
)

// WarmStorageAddresses aliases the FWSS addresses (root of trust)
var WarmStorageAddresses = map[Network]common.Address{
	NetworkMainnet:     FWSSAddressMainnet,
	NetworkCalibration: FWSSAddressCalibration,
	NetworkDevnet:      FWSSAddressDevnet,
}

// derived addresses - read from FWSS contracts
var (
	PaymentsAddresses = map[Network]common.Address{
		NetworkMainnet:     common.HexToAddress("0x23b1e018F08BB982348b15a86ee926eEBf7F4DAa"),
		NetworkCalibration: common.HexToAddress("0x09a0fDc2723fAd1A7b8e3e00eE5DF73841df55a0"),
		NetworkDevnet:      common.HexToAddress("0xFD61fA68CB8F70dfC35a4AB244703e39BaB9F352"),
	}

	WarmStorageStateViewAddresses = map[Network]common.Address{
		NetworkMainnet:     common.HexToAddress("0x638a4986332bF9B889E5D7435B966C5ecdE077Fa"),
		NetworkCalibration: common.HexToAddress("0x53d235D474585EC102ccaB7e0cdcE951dD00f716"),
		NetworkDevnet:      common.HexToAddress("0xfcDDd1E5BC2658fB7483B8e2fa72d8368756F5A3"),
	}

	PDPVerifierAddresses = map[Network]common.Address{
		NetworkMainnet:     common.HexToAddress("0xBADd0B92C1c71d02E7d520f64c0876538fa2557F"),
		NetworkCalibration: common.HexToAddress("0x85e366Cf9DD2c0aE37E963d9556F5f4718d6417C"),
		NetworkDevnet:      common.HexToAddress("0xc72B3D661fcCeBfDf95d3377C2133dCE7bc5cb2e"),
	}

	SPRegistryAddresses = map[Network]common.Address{
		NetworkMainnet:     common.HexToAddress("0xf55dDbf63F1b55c3F1D4FA7e339a68AB7b64A5eB"),
		NetworkCalibration: common.HexToAddress("0x839e5c9988e4e9977d40708d0094103c0839Ac9D"),
		NetworkDevnet:      common.HexToAddress("0x123DeEe2aD1d87757cb59eFA77b4975CbfB8be9d"),
	}

	SessionKeyRegistryAddresses = map[Network]common.Address{
		NetworkMainnet:     common.HexToAddress("0x74FD50525A958aF5d484601E252271f9625231aB"),
		NetworkCalibration: common.HexToAddress("0x518411c2062E119Aaf7A8B12A2eDf9a939347655"),
		NetworkDevnet:      common.HexToAddress("0xaF69542d01111EdfB7B63Aa974E6A2c9A31EA1E9"),
	}
)
